name: Build Application

on: workflow_dispatch

concurrency: job-${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Loop
        run: |
          max_attempts=10
          attempt=1
      
          while [ $attempt -le $max_attempts ]; do
                
              if [ $attempt -eq 8 ]; then
                  echo
                  break
              else
                  echo "IP exception rule not found. Retrying in 5 seconds..."
                  sleep 5
                  ((attempt++))
              fi
          done

          if [ $attempt -gt $max_attempts ]; then
              echo "Maximum number of attempts reached. Exiting..."
              exit 1
          fi
