name: Build Application

on: workflow_dispatch

concurrency: job-${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Loop
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
              $maxAttempts = 10
              $attempt = 1
              while ($attempt -le $max_attempts) {
                  Write-Output "Iteration passed"
                  
                  if ($attempt -eq 8) {
                      Write-Output "Find address"
                      break
                  }
                  else {
                      Write-Output "IP exception rule not found. Retrying in 1 seconds..."
                      echo "IP exception rule not found. Retrying in 1 seconds..."
                      sleep 1
                      ((attempt++))
                  }
                }

              if ($attempt -gt $max_attempts) {
                  Write-Output "Maximum number of attempts reached. Exiting..."
                  exit 1
              }
